#!/usr/bin/env python3

"""Check for new versions of freedv-gui by reading Github tags."""

import os
import sys

from github import Github

import semver

from pkgbuild import SRCINFO


# Get the versions on Github and the repository.
g = Github(os.environ.get("GITHUB_ACCESS_TOKEN"))
upstream = g.get_repo("drowe67/freedv-gui").get_tags()[0].name[1:]
current = SRCINFO("freedv-gui/.SRCINFO").content["pkgver"]

print("Upstream version: %s" % upstream)
print("AUR version: %s" % current)

try:
    semver.parse(current)
except ValueError:
    current += ".0"

try:
    semver.parse(upstream)
except ValueError:
    upstream += ".0"

if semver.compare(current, upstream) < 0:
    print("Package is out of date.")
    sys.exit(1)
elif semver.compare(current, upstream) > 0:
    print("Package is newer than upstream release.")
    sys.exit(1)
