#!/usr/bin/env python2

"""Check for new versions of python-pyxel by reading Github tags."""

import json
import re
import sys
from urllib2 import urlopen

from _utils import get_current_version


# Get the latest version on Github
response = urlopen("https://api.github.com/repos/kitao/pyxel/tags")
regex = re.compile(r"^v(?P<version>\d+\.\d+\.\d+)$")
matches = [regex.match(tag["name"]) for tag in json.loads(response.read())]
versions = [m.group("version") for m in matches if m is not None]
upstream = max(versions)

current = get_current_version("python-pyxel")

print("Upstream version: %s" % upstream)
print("AUR version: %s" % current)

if current < upstream:
    print("Package is out of date.")
    sys.exit(1)
elif current > upstream:
    print("Package is newer than upstream release.")
    sys.exit(1)
