#!/usr/bin/env python2

"""Check for new versions of vna_j by parsing the website."""

import re
import sys
from urllib2 import urlopen

from _utils import get_current_version


# Get the latest version from the website.
response = urlopen(
    "https://vnaj.dl2sba.com/index.php?option=com_content&view=article&id=11:downloads&catid=16&Itemid=118"
)
regex = re.compile(r"download\.dl2sba\.com/vnaj/(?P<version>\d+\.\d+\.\d+)")

versions = [m.group("version") for m in regex.finditer(response.read())]
upstream = max(versions)

current = get_current_version("vna_j")

print("Upstream version: %s" % upstream)
print("AUR version: %s" % current)

if current < upstream:
    print("Package is out of date.")
    sys.exit(1)
elif current > upstream:
    print("Package is newer than upstream release.")
    sys.exit(1)
